unique_ids:
  assets:
    standard-page.html: 6QKPF5SPTIB2AJDQ72DMWKALQCHC5E4U
    theme.css: YLYJSRFUKYFZHE4ZR7TGYT4UUAHREPFA
  forms:
    Form1: QCYJG2D63BNFCYYNS2D7C2BUEHIGYAJ5
  modules: {}
  scripts: {}
  server_modules: {}
